#!/bin/bash

#######################################################
#  PREPARE PAMA-NYUNGAN COGNATE AND PHONOTACTIC DATA  #
#  FOR PHYLOGENETIC ANALYSIS WITH BEAST	#
#			#
#    Jayden Macklin-Cordes		#
#    Created: 2019-07-11		#
#    Last edit: 2019-07-22		#
#			#
#######################################################

# INPUT:
#    - A directory called Bouckaert_etal, containing files Pny10-Export.tsv and pny10.pl
#    - A directory called Data_prep, containing file prepare_pn_phonotactic_traits.R
# OUTPUT:
#    - A directory called Data, containing pny10_cognates_[date].nex, biphone_traits_[date].tsv and soundclass_traits_[date].tsv
#    - In Data_prep, the file pny10_filtered_[date].pl and Pny10-Export_filtered_[date].tsv
# REQUIREMENTS:
#    - Software: bash, R (with packages: Ausphonlex, tidyverse), Perl
#    - NB: Script has been run on hardware/software as described below.
#          No specific versioning requirements are known, but script has not been tested on alternative setups so success is not guaranteed.
#    - Unfortunately, on line 71 of the R script, there is a hard-coded filepath to a data file in the Ausphonlex package, Ausphonlex/dbs/Maps-DB-wordlists.csv.
#      Currently, this R script will only work if that filepath is accurate.
# USAGE:
#    - Make sure this executable file is saved in your terminal's $PATH variable (check 'echo $PATH')
#    - If not, either move file to somewhere in the $PATH (e.g. usr/bin) or add its location to the PATH.
#    - Make sure input directories are saved in the current working directory
#    - Run command prepare_pn_data

# SOURCES
#
# Pama-Nyungan cognate data is sourced from the Zenodo record for the following reference:
#
#   Bouckaert, Remco, Bowern, Claire, & Atkinson, Quentin. (2018). 
#   The origin and expansion of Pama–Nyungan languages across Australia: Cognate Data (Version 1.) [Data set].
#   Nature Ecology and Evolution. http://doi.org/10.1038/s41559-018-0489-3
#
#   Zenodo record: https://zenodo.org/record/1320471 (Accessed, downloaded 2019-07-08)
#
# The Zenodo record contains a spreadsheet of original cognate data and a Perl script for converting the data to Nexus format.
# The Perl script was created for Bouckaert et al.'s in-house research purposes and requires a little intervention to insert the cognate data into the script successfully.
# Original Zenodo downloads are preserved, untouched, in Bouckaert_etal directory.

# RUN HISTORY
#
# Last run: 22-07-2019
#
# With following system/software:
# 
# $ sw_vers
# ProductName:	Mac OS X
# ProductVersion:	10.12.6
# BuildVersion:	16G2016
# 
# $ bash --version
# GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
# Copyright (C) 2007 Free Software Foundation, Inc.
# 
# $ R --version
# R version 3.5.1 (2018-07-02) -- "Feather Spray"
# Copyright (C) 2018 The R Foundation for Statistical Computing
# Platform: x86_64-apple-darwin15.6.0 (64-bit)
#
# R is free software and comes with ABSOLUTELY NO WARRANTY.
# You are welcome to redistribute it under the terms of the
# GNU General Public License versions 2 or 3.
# For more information about these matters see
# http://www.gnu.org/licenses/.
#
# $ perl --version
# This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
# (with 2 registered patches, see perl -V for more detail)
# 
# Copyright 1987-2013, Larry Wall
# 
# Perl may be copied only under the terms of either the Artistic License or the
# GNU General Public License, which may be found in the Perl 5 source kit.
# 
# Complete documentation for Perl, including FAQ lists, should be found on
# this system using "man perl" or "perldoc perl".  If you have access to the
# Internet, point your browser at http://www.perl.org/, the Perl Home Page.
#
#########################################################################################

# Run R script to prepare phonotactic trait datasets, filter cognate data
# See R script for more details

date=`date '+%Y-%m-%d'`

mkdir Data
Rscript Data_prep/prepare_pn_phonotactic_traits.R

# Copy original cognate data to Data folder, delete single quotes from glosses/translations (these mess up the Perl script)
sed -i '' "s/'//g" Data_prep/Pny10-Export_filtered_$date.tsv

# Copy original Perl script to Data folder, delete the first five lines (where the cognate dataset will be inserted)
sed '1,5d' Bouckaert_etal/pny10.pl > Data_prep/temp.pl

# Wrap cognate data in Perl command $='[DATA]'; and concatenate to Perl Script
echo "\$s='$(cat Data_prep/Pny10-Export_filtered_$date.tsv)';" | cat - Data_prep/temp.pl > Data_prep/pny10_filtered_$date.pl
rm Data_prep/temp.pl

# Run the Perl script and write output to nexus file
filename="pn_cognates_$date.nex"
perl Data_prep/pny10_filtered_$date.pl > Data/$filename
