# Prepare subgroup files to import into Beauti
# Jayden Macklin-Cordes
# # # # # # # # # # # # # # # # # # # # # # # #

# This script generates a simple text file for each Pama-Nyungan subgroup
# for importing clade priors into Beauti.
# Each taxon in our dataset is allocated to its corresponding subgroup in 
# Bouckaert, Bowern and Atkinson 2018.
# This is done by matching taxa to subgroups in the "Languages-StandardLangs.csv" 
# spreadsheet then making some manual adjustments to match Bouckaert, Bowern and 
# Atkinson 2018.
# Note that several subgroups contain only one language. These don't need to be 
# imported into Beauti (they're uninformative without ages) but 
# the script generates them anyway for ease of reproducibility if more languages
# are added in the future.

# Get subgroup info
lg_subgroups <- read_csv("../Data/CB_raw/Languages-StandardLangs.csv") %>%
  filter(Ascii_Name %in% bindat$tip_label) %>%
  select(Ascii_Name, `TEMP@SubgroupName`)
# Manual adjustments to match Bouckaert, Bowern and Atkinson (2018)
lg_subgroups$`TEMP@SubgroupName`[lg_subgroups$`TEMP@SubgroupName` == "Yolŋu"] <- "Yolngu"
lg_subgroups$`TEMP@SubgroupName`[lg_subgroups$`TEMP@SubgroupName` %in% c("Dyirbalic", "Maric", "Nyawaygic", "Paman")] <- "PamaMaric"
lg_subgroups$`TEMP@SubgroupName`[lg_subgroups$`TEMP@SubgroupName` == "Kanyara-Martatha"] <- "Kanyara-Mantharta"
lg_subgroups$`TEMP@SubgroupName`[lg_subgroups$`TEMP@SubgroupName` == "Mirniny"] <- "SouthWest"
lg_subgroups$`TEMP@SubgroupName`[lg_subgroups$`TEMP@SubgroupName` == "Pilbara"] <- "Ngayarta"
lg_subgroups[lg_subgroups$Ascii_Name == "Paakantyi",2] <- "PaakantyiRegion"
lg_subgroups[lg_subgroups$Ascii_Name == "Bandjalang",2] <- "Bandjalangic"
# Manually add lgs missing from Languages-StandardLangs spreadsheet (or listed as "no subgroup defined")
# to match Bouckaert, Bowern and Atkinson (2018)
missing_lgs <- tibble("Ascii_Name" = c("Yaygirr",
                                       "WalmajarriHR", 
                                       "Tharrgari", 
                                       "WesternArrarnta", 
                                       "MangalaMcK",
                                       "Ngadjumaya",
                                       "Mbakwithi"),
                      "TEMP@SubgroupName" = c("Gumbaynggiric",
                                              "Ngumpin-Yapa",
                                              "Kanyara-Mantharta",
                                              "Arandic",
                                              "Marrngu",
                                              "SouthWest",
                                              "PamaMaric")
)
lg_subgroups <- bind_rows(lg_subgroups, missing_lgs)

# Get well-formed list of subgroup names
subgroups <- unique(lg_subgroups$`TEMP@SubgroupName`)
subgroups[subgroups == "no subgroup defined"] <- NA
subgroups <- subgroups[!is.na(subgroups)]
#subgroups <- gsub("-| ", "", subgroups)

write_subgroup_files <- function (lg_subgroups, bindat) {
  subgroup_dfs <- lapply(subgroups, function (i) {filter(lg_subgroups, `TEMP@SubgroupName` == i) %>%
      select(Ascii_Name)})
  names(subgroup_dfs) <- gsub("-| ", "", subgroups)
  lapply(1:length(subgroup_dfs), 
         function (i) write_tsv(subgroup_dfs[[i]],
                                paste0("../Data/subgroups/", names(subgroup_dfs[i]), ".txt"),
                                col_names = FALSE))
}

write_subgroup_files(lg_subgroups)

# Tip dates (taken from BEAST XML file from Bouckaert et al. 2018)
tip_dates <- c(Yanda = 100,
Badjiri = 40,
Guwa = 100,
Adnyamathanha = 25,
AghuTharrnggala = 30,
Alngith = 0,
Alyawarr = 0,
Aminungo = 120,
Antekerrepenhe = 30,
Arabana = 30,
Awabakal = 170,
Ayapathu = 0,
Badimaya = 10,
Balkurra = 160,
Bandjalang = 20,
Barna = 0,
BarrowPoint = 40,
Batyala = 50,
Belyando = 0,
BidyaraGungabula = 30,
Bilinarra = 10,
Bindal = 30,
Bindjali = 0,
Biri = 30,
Birrpayi = 130,
Bularnu = 30,
Bunganditj = 130,
CentralAnmatyerr = 0,
ChampionBay = 0,
Colac = 140,
Coobenpil = 0,
Coonambella = 0,
Dalla = 0,
Darkinyung = 120,
DawsonRiver = 120,
Dhangu = 0,
Dharawal = 130,
Dharawala = 0,
Dharuk = 210,
Dharumbal = 0,
Dhayyi = 0,
Dhudhuroa = 150,
Dhurga = 40,
Dhuwal = 0,
Dhuwala = 0,
Diyari = 30,
Djabugay = 30,
Djambarrpuyngu = 0,
Djapu = 0,
Djinang = 0,
Durubul = 60,
Duungidjawu = 50,
Dyirbal = 30,
Eucla = 120,
FlindersIsland = 40,
Gamilaraay = 40,
Ganggalida = 0,
Gangulu = 30,
Garlali = 35,
Githabul = 0,
Golpa = 0,
GoorengGooreng = 40,
Gudang = 0,
Gudjal = 10,
GuguBadhun = 0,
Gugumini = 0,
Gumatj = 0,
Gumbaynggir = 30,
Gunditjmara = 140,
Gundungurra = 150,
Gunggari = 50,
Gunya = 30,
Gupapuyngu = 0,
Gurindji = 10,
GuuguYimidhirr = 30,
Guwamu = 50,
Guwar = 0,
Guyani = 130,
HOPKINSRIVER = 0,
Ikarranggal = 0,
Injinoo = 0,
IrwinMurchison = 0,
Iyora = 210,
Jaitmatang = 160,
Jaru = 10,
JaruMcC = 10,
Jiwarli = 20,
Jiwarliny = 10,
KKY = 20,
KLY = 20,
Kaanju = 30,
Kalkatungu = 40,
Kamilaroi = 180,
Kaniyang = 0,
Karajarri = 10,
KarajarriNW = 70,
Kariyarra = 10,
Karree = 120,
Kartujarra = 10,
Karuwali = 100,
Katthang = 120,
Kaurna = 180,
Kayardild = 0,
Kaytetye = 30,
Keerraywoorroong = 100,
Keramin = 160,
KokNar = 0,
KokoBera = 0,
KuguNganhcara = 20,
Kukatj = 20,
Kukatja = 10,
KukuWura = 0,
KukuYalanji = 20,
Kungadutyi = 40,
Kungkari = 100,
Kunjen = 0,
Kurnu = 40,
Kurrama = 10,
Kurtjar = 30,
KuukThaayorre = 0,
KuukuYau = 10,
Lardil = 0,
Linngithigh = 40,
Mabuiag = 95,
Malgana = 30,
Malngin = 10,
Malyangapa = 50,
MangalaMcK = 30,
MangalaNW = 70,
Manjiljarra = 0,
Margany = 30,
MartuWangka = 10,
Martuthunira = 0,
MaryRiverandBunyaBunyaCountry = 120,
MathiMathi = 40,
MayiKulan = 80,
MayiKutuna = 40,
MayiThakurti = 40,
MayiYapi = 40,
Mbabaram = 30,
Mbakwithi = 20,
Mbiywom = 0,
Minjungbal = 100,
Minkin = 0,
Mirniny = 50,
Mithaka = 40,
Moneroo = 114,
MountFreelingDiyari = 120,
Mpalityan = 0,
Mudburra = 10,
MudburraMcC = 10,
MuliarraTribe = 114,
Muruwari = 40,
Narrungga = 160,
NatalDowns = 0,
NerangCreek = 0,
NewNorciaandLeschenaultBay = 0,
Ngaanyatjarra = 10,
Ngadjumaya = 50,
Ngadjuri = 150,
Ngaiawang = 170,
Ngamini = 30,
Ngardily = 10,
Ngarigu = 110,
Ngarinyman = 10,
Ngarla = 10,
Ngarluma = 10,
Ngarrindjeri = 160,
Ngawun = 100,
NggoiMwoi = 120,
Nggoth = 0,
Ngiyambaa = 30,
Nguburindi = 0,
Ngunawal = 110,
Nhanta = 10,
Nhirrpi = 50,
NorthernMangarla = 30,
NorthernNyangumarta = 30,
Ntrangith = 0,
Nukunu = 0,
Nyamal = 10,
Nyangumarta = 10,
Nyawaygi = 0,
Nyungar = 70,
Olkola = 0,
Paakantyi = 40,
Pakanh = 10,
Pallanganmiddang = 140,
Panyjima = 20,
Parnkala = 160,
Payungu = 20,
Piangil = 130,
Pinjarra = 0,
PintupiLuritja = 10,
Pirriya = 120,
Pitjantjatjara = 10,
PittaPitta = 30,
PortMacQuarie = 120,
Punthamara = 40,
Purduna = 0,
Rirratjingu = 0,
Ritharrngu = 20,
SouthernWalmajarri = 30,
SteeleGDG = 0,
THETATIARRACOUNTRY = 0,
Tagalag = 100,
Thalanyji = 0,
Thanggatti = 0,
Tharrgari = 0,
Thaynakwith = 0,
Thurrawal = 0,
Tjapwurrung = 0,
TweedRiverandPointDangar = 120,
Umpila = 20,
Umpithamu = 0,
UpperBrisbaneRiver = 0,
Uradhi = 0,
UwOykangand = 0,
Wadikali = 60,
Wadjabangayi = 120,
Wailwan = 120,
Wajarri = 10,
WakaWaka = 0,
Wakaya = 20,
Walangama = 0,
WalmajarriBilliluna = 10,
WalmajarriHR = 20,
WalmajarriNW = 70,
Wangkajunga = 0,
Wangkangurru = 30,
Wangkatja = 10,
Wangkayutyuru = 30,
Wangkumara = 40,
WangkumaraMcDWur = 30,
Wardandi = 100,
Wargamay = 30,
Warlmanpa = 10,
Warlpiri = 0,
Warluwarra = 30,
Warnman = 10,
Warriyangga = 20,
Warrnambool = 0,
Warumungu = 10,
Warungu = 30,
Wathawurrung = 100,
Wathiwathi = 160,
Watjuk = 100,
Wellington = 170,
WembaWemba = 40,
WesternArrarnta = 0,
WikMuminh = 0,
WikMungkan = 30,
WikNgatharr = 0,
Wiradjuri = 30,
Wirangu = 40,
Woiwurrung = 100,
Wulguru = 0,
YabulaYabula = 120,
Yadhaykenu = 0,
Yagara = 60,
Yalarnnga = 30,
Yambina = 0,
Yandruwandha = 30,
Yangarella = 0,
Yangkaal = 0,
Yannhangu = 0,
Yanyuwa = 30,
Yardliyawarra = 100,
Yarluyandi = 30,
Yawarrawarrka = 30,
Yaygirr = 0,
Yidiny = 25,
Yindjibarndi = 30,
Yindjilandji = 50,
Yingkarta = 0,
Yinhawangka = 0,
Yiningay = 100,
Yinwum = 0,
YirYoront = 0,
Yirandali = 120,
YithaYitha = 160,
YortaYorta = 120,
Yugambeh = 30,
Yugarabul = 0,
Yulparija = 20,
Yuwaalaraay = 30,
Zorc = 0,
Bayali = 120,
Bibbulman = 120,
Bigambal = 120,
CoopersCreek = 120,
GlenInnes = 120,
GraniteRange = 120,
Hawkesbury = 120,
Janday = 120,
Kalaamaya = 120,
KingsCreekandtheGeorginaRiver = 120,
LakeHindmarsh = 120,
LowerBurdekin = 120,
NedsCornerStation = 120,
PytuReach = 120,
RoxburghDownsLowerGeorgina = 120,
Tambo = 120,
Tenterfield = 120,
UpperParoo = 120,
Wanamara = 120)

tip_dates_df <- tibble(tip_label = names(tip_dates), years_BP = tip_dates) %>%
  filter(tip_label %in% lg_subgroups$Ascii_Name)
write_tsv(tip_dates_df, "../Data/tip_dates.tsv", col_names = FALSE)
